name: pr_4
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter


  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

  assets:
    - lib/assets/groups_brown.png
    - lib/assets/groups_pink.png
    - lib/assets/groups_blue.png

    - lib/assets/clock_brown.png
    - lib/assets/clock_blue.png
    - lib/assets/clock_pink.png
  uses-material-design: true


